### ISSUE TITLE
Digital clock tutorial ready function

### ISSUE THREAD

**Issue by wfalkwallace** [googlecreativelab/coder-projects#1]
The digital clock tutorial [here](http://googlecreativelab.github.io/coder-projects/projects/digital_clock/) writes the jquery ready function incorrectly at the beginning of the tutorial. It is fixed later in the tutorial. The first writes `$(document).ready = function() {` and has a misaligned right-paren at its close; the second example properly shows `$(document).ready( function() {` with its now correctly matching close `});`

![screenshot 2013-12-24 10 41 18](https://f.cloud.github.com/assets/2934046/1806531/203ea5ac-6cb2-11e3-8ad2-27412559aa22.png)

![screenshot 2013-12-24 10 44 49](https://f.cloud.github.com/assets/2934046/1806542/59708214-6cb2-11e3-8c46-7694e5abac2a.png)

**Comment by jmstriegel** [comment]
Thanks for the catch!
