### ISSUE TITLE
Modern Mondrian Title

### ISSUE THREAD

**Issue by benforshey** [googlecreativelab/coder-projects#2]
Thanks for the the great projects! Found a spelling error in the title of the "Modern Mondrian" project.

Once opened, the project's header has "Mondrian" misspelled as "Mondiran". 
![screen shot 2014-01-09 at 12 46 42 pm](https://f.cloud.github.com/assets/2887467/1881997/63ec8624-796f-11e3-8155-d9b8aaa91fc5.png)

**Comment by jmstriegel** [comment]
Fixed! Thanks for the catch.
